### ISSUE TITLE
Possible solution for the compatibility issue

### ISSUE THREAD

**Issue by aarkhipov40** [flixpressllc/ReactBasicTemplateEditor#59]
Ideally, we would slowly phase out the flash, but it seems like a lot of our users are still struggling.... so, I'm wondering if the ideal solution would be a dynamic switching based on Modernizr script from the Browser app.

So, we devise it as a "fallback" type of scheme.   If it doesn't detect the newer browsers that we have tested without any issues, then we would fall back on the legacy templates.

**Comment by happycollision** [comment]
I am happy to do some dynamic switching, but I'd much rather address the issues that they are having directly. Otherwise we might be holding onto legacy software for reasons that are easily fixed. We would also have to hold back new features from them (youtube links, better color pickers, etc.) unless we are going to continue to update the flash application.

**Comment by happycollision** [comment]
I was able to reproduce the issue in a browser session on crossbrowsertesting.com. They only allow 5 minutes while you are a free user, so I couldn't get and further.

I am in the process of trying to run a virtual machine running linux with an old version of Chrome. Then I should at least be able to properly debug the issue.

**Comment by happycollision** [comment]
I have successfully reproduced the issue on my local machine by running an old version of Chrome on Ubuntu. When I come in tomorrow, the first thing I will do is to fix the bug.
